# Site
title:              Felipe Tavares de Melo
bio:                'Analista e Desenvolvedor de Software'
description:        "Soluções Web full-stack, Desktop, Mobile e IoT (Internet of Things)"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           true   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             pt_BR
url:                https://felipetavaresmelo.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   felipetavaresmelo

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              felipetavaresmelo@gmail.com
twitter:            ftavaresmelo
facebook:           felipetavaresmelo
github-url:         felipetavaresmelo
stackoverflow:      10817619/felipe-tavares-de-melo   from a "http://stackoverflow.com/users/10817619/felipe-tavares-de-melo" link
linkedin:           felipetavaresmelo
#xing:              username
instagram:          felipetm
#lastfm:            username
#tumblr:            username
medium:            '@felipetavaresmelo'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
youtube:            felipetavaresmelo
youtube-channel:    FelipeTavaresDeMelo85
soundcloud:         felipetavaresmelo
#weibo:             username
flickr:             felipetavaresmelo
codepen:            ftavaresmelo
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
